In [3]:
import numpy as np
import pandas as pd

In [3]:
url = 'https://acehacker.com/microsoft/engage2022/cars_engage_2022.csv'

In [4]:
cars = pd.read_csv(url)

## Exploratory Data Analysis and Cleaning of Data

In [5]:
cars.head()

,Unnamed: 0,Make,Model,Variant,Ex-Showroom_Price,Displacement,Cylinders,Valves_Per_Cylinder,Drivetrain,Cylinder_Configuration,...,Leather_Wrapped_Steering,Automatic_Headlamps,Engine_Type,ASR_/_Traction_Control,Cruise_Control,USB_Ports,Heads-Up_Display,Welcome_Lights,Battery,Electric_Range
0,0,Tata,Nano Genx,Xt,"Rs. 2,92,667",624 cc,2.0,2.0,RWD (Rear Wheel Drive),In-line,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Tata,Nano Genx,Xe,"Rs. 2,36,447",624 cc,2.0,2.0,RWD (Rear Wheel Drive),In-line,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,Tata,Nano Genx,Emax Xm,"Rs. 2,96,661",624 cc,2.0,2.0,RWD (Rear Wheel Drive),In-line,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,Tata,Nano Genx,Xta,"Rs. 3,34,768",624 cc,2.0,2.0,RWD (Rear Wheel Drive),In-line,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,Tata,Nano Genx,Xm,"Rs. 2,72,223",624 cc,2.0,2.0,RWD (Rear Wheel Drive),In-line,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
cars.drop(columns = 'Unnamed: 0' , inplace = True)

In [7]:
cars.head()

,Make,Model,Variant,Ex-Showroom_Price,Displacement,Cylinders,Valves_Per_Cylinder,Drivetrain,Cylinder_Configuration,Emission_Norm,...,Leather_Wrapped_Steering,Automatic_Headlamps,Engine_Type,ASR_/_Traction_Control,Cruise_Control,USB_Ports,Heads-Up_Display,Welcome_Lights,Battery,Electric_Range
0,Tata,Nano Genx,Xt,"Rs. 2,92,667",624 cc,2.0,2.0,RWD (Rear Wheel Drive),In-line,BS IV,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Tata,Nano Genx,Xe,"Rs. 2,36,447",624 cc,2.0,2.0,RWD (Rear Wheel Drive),In-line,BS IV,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Tata,Nano Genx,Emax Xm,"Rs. 2,96,661",624 cc,2.0,2.0,RWD (Rear Wheel Drive),In-line,BS IV,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Tata,Nano Genx,Xta,"Rs. 3,34,768",624 cc,2.0,2.0,RWD (Rear Wheel Drive),In-line,BS IV,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Tata,Nano Genx,Xm,"Rs. 2,72,223",624 cc,2.0,2.0,RWD (Rear Wheel Drive),In-line,BS IV,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [33]:
cars.iloc[0:3,0:50].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 50 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Make                            3 non-null      object
 1   Model                           3 non-null      object
 2   Variant                         3 non-null      object
 3   Ex-Showroom_Price               3 non-null      object
 4   Displacement                    3 non-null      object
 5   Cylinders                       3 non-null      float64
 6   Valves_Per_Cylinder             3 non-null      float64
 7   Drivetrain                      3 non-null      object
 8   Cylinder_Configuration          3 non-null      object
 9   Emission_Norm                   3 non-null      object
 10  Engine_Location                 3 non-null      object
 11  Fuel_System                     3 non-null      object
 12  Fuel_Tank_Capacity              3 non-null      object
 13  Fuel_Type                       3 non-null      object
 14  Height                          3 non-null      object
 15  Length                          3 non-null      object
 16  Width                           3 non-null      object
 17  Body_Type                       3 non-null      object
 18  Doors                           3 non-null      float64
 19  City_Mileage                    2 non-null      object
 20  Highway_Mileage                 0 non-null      object
 21  ARAI_Certified_Mileage          2 non-null      object
 22  ARAI_Certified_Mileage_for_CNG  1 non-null      object
 23  Kerb_Weight                     3 non-null      object
 24  Gears                           3 non-null      object
 25  Ground_Clearance                3 non-null      object
 26  Front_Brakes                    3 non-null      object
 27  Rear_Brakes                     3 non-null      object
 28  Front_Suspension                3 non-null      object
 29  Rear_Suspension                 3 non-null      object
 30  Front_Track                     3 non-null      object
 31  Rear_Track                      3 non-null      object
 32  Front_Tyre_&_Rim                3 non-null      object
 33  Rear_Tyre_&_Rim                 3 non-null      object
 34  Power_Steering                  2 non-null      object
 35  Power_Windows                   1 non-null      object
 36  Power_Seats                     0 non-null      object
 37  Keyless_Entry                   1 non-null      object
 38  Power                           3 non-null      object
 39  Torque                          3 non-null      object
 40  Odometer                        3 non-null      object
 41  Speedometer                     3 non-null      object
 42  Tachometer                      3 non-null      object
 43  Tripmeter                       3 non-null      object
 44  Seating_Capacity                3 non-null      float64
 45  Seats_Material                  3 non-null      object
 46  Type                            3 non-null      object
 47  Wheelbase                       3 non-null      object
 48  Wheels_Size                     3 non-null      object
 49  Start_/_Stop_Button             1 non-null      object
dtypes: float64(4), object(46)
memory usage: 1.3+ KB

In [8]:
def con_var_summary(x):
    return pd.Series([x.dtype
                      ,x.isnull().count()
                      , x.isnull().sum() ,x.mean() , x.sum() , x.var() ,x.std(), x.min() ,
                      x.quantile(0.01) ,x.quantile(0.05) ,x.quantile(0.1) ,x.quantile(0.25) ,
                      x.quantile( ) ,x.quantile(0.75) ,x.quantile(0.90) ,x.quantile(0.95) ,x.quantile(0.99) ,
                     x.quantile(1)]
                    ,index = ['data_type' ,'N' , 'nulls' , 'mean','sum ','VAR' , 'STD' , 'MIN'
                             ,'P1','P5','P10' , 'Q1' , 'Q2' , 'Q3' , 'P90' ,'P95' , 'P99' , 'MAX'])

In [9]:
cars.rename(columns = {'Ex-Showroom_Price' : 'Ex-Showroom_Price (in Rs.)' , 'Displacement' : 'Displacement (in cc)',
            'Fuel_Tank_Capacity': 'Fuel_Tank_Capacity (in litres)' ,'Height' : 'Height (in mm)', 'Length' : 'Length (in mm)',
            'Width' : 'width (in mm)' ,'City_Mileage':'City_Mileage (km/litre)' ,
             'Highway_Mileage':'Highway_Mileage (km/litre)','ARAI_Certified_Mileage':'ARAI_Certified_Mileage (km/litre)',
           'ARAI_Certified_Mileage_for_CNG':'ARAI_Certified_Mileage_for_CNG (km/kg)','Kerb_Weight':'Kerb_Weight (kg)',
            'Ground_Clearance':'Ground_Clearance (in mm)' , 'Front_Track':'Front_Track (in mm)',
            'Rear_Track':'Rear_Track (in mm)','Wheelbase':'Wheelbase (in mm)','Boot_Space':'Boot_Space (in litres)',
            } , inplace = True)

In [10]:
cars.columns

Index(['Make', 'Model', 'Variant', 'Ex-Showroom_Price (in Rs.)',
       'Displacement (in cc)', 'Cylinders', 'Valves_Per_Cylinder',
       'Drivetrain', 'Cylinder_Configuration', 'Emission_Norm',
       ...
       'Leather_Wrapped_Steering', 'Automatic_Headlamps', 'Engine_Type',
       'ASR_/_Traction_Control', 'Cruise_Control', 'USB_Ports',
       'Heads-Up_Display', 'Welcome_Lights', 'Battery', 'Electric_Range'],
      dtype='object', length=140)

In [11]:
cars.select_dtypes(['int64','float64']).apply(con_var_summary)

,Cylinders,Valves_Per_Cylinder,Doors,Seating_Capacity,Number_of_Airbags,USB_Ports
data_type,float64,float64,float64,float64,float64,float64
N,1276,1276,1276,1276,1276,1276
nulls,66,102,4,6,135,1247
mean,4.380992,3.977853,4.550314,5.270079,3.787029,1.793103
sum,5301.0,4670.0,5788.0,6693.0,4321.0,52.0
VAR,2.758778,0.695161,0.559229,1.311555,6.362498,0.598522
STD,1.660957,0.833763,0.747816,1.145231,2.522399,0.773642
MIN,2.0,1.0,2.0,2.0,1.0,1.0
P1,3.0,2.0,2.0,2.0,1.0,1.0
P5,3.0,4.0,3.0,4.0,2.0,1.0
P10,3.0,4.0,4.0,5.0,2.0,1.0
Q1,4.0,4.0,4.0,5.0,2.0,1.0
Q2,4.0,4.0,5.0,5.0,2.0,2.0
Q3,4.0,4.0,5.0,5.0,6.0,2.0
P90,6.0,4.0,5.0,7.0,8.0,3.0
P95,8.0,4.0,5.0,7.0,8.0,3.0
P99,12.0,4.0,5.0,9.0,10.0,3.0
MAX,16.0,16.0,5.0,16.0,14.0,3.0

In [12]:
def cat_var_summary(x):
    return pd.Series([x.dtype
                      ,x.isnull().count()
                      , x.isnull().sum()]
                    ,index = ['data_type' ,'N' , 'nulls'])

In [13]:
cars.select_dtypes(['object']).apply(cat_var_summary)

,Make,Model,Variant,Ex-Showroom_Price (in Rs.),Displacement (in cc),Drivetrain,Cylinder_Configuration,Emission_Norm,Engine_Location,Fuel_System,...,Paddle_Shifters,Leather_Wrapped_Steering,Automatic_Headlamps,Engine_Type,ASR_/_Traction_Control,Cruise_Control,Heads-Up_Display,Welcome_Lights,Battery,Electric_Range
data_type,object,object,object,object,object,object,object,object,object,object,...,object,object,object,object,object,object,object,object,object,object
N,1276,1276,1276,1276,1276,1276,1276,1276,1276,1276,...,1276,1276,1276,1276,1276,1276,1276,1276,1276,1276
nulls,75,0,0,0,12,7,13,11,43,8,...,972,689,774,1242,834,727,1225,1207,1263,1259

In [58]:
cars['Ex-Showroom_Price (in Rs.)']

0        Rs. 2,92,667
1        Rs. 2,36,447
2        Rs. 2,96,661
3        Rs. 3,34,768
4        Rs. 2,72,223
            ...
1271    Rs. 13,02,000
1272    Rs. 14,21,000
1273    Rs. 14,31,000
1274    Rs. 12,01,000
1275    Rs. 68,62,560
Name: Ex-Showroom_Price (in Rs.), Length: 1276, dtype: object

In [14]:
cars['Ex-Showroom_Price (in Rs.)'] = [i.replace('Rs. ','') for i in cars['Ex-Showroom_Price (in Rs.)']]

In [28]:
cars['Ex-Showroom_Price (in Rs.)'] = [i.replace(',','') for i in cars['Ex-Showroom_Price (in Rs.)']]

In [29]:
cars['Ex-Showroom_Price (in Rs.)'] = cars['Ex-Showroom_Price (in Rs.)'].astype(int)

In [22]:
cars['Displacement (in cc)'] = cars['Displacement (in cc)'].astype(str)

In [24]:
cars['Displacement (in cc)'] = [i.replace(' cc','') for i in cars['Displacement (in cc)']]

In [43]:
cars[cars['Displacement (in cc)'] == 'nan']['Displacement (in cc)']

Series([], Name: Displacement (in cc), dtype: object)

In [89]:
cars.loc[cars['Displacement (in cc)'].isna(),'Displacement (in cc)'] = np.nan

In [91]:
cars['Displacement (in cc)'] = cars['Displacement (in cc)'].astype(float)

In [95]:
cars['Fuel_Tank_Capacity (in litres)'] = cars['Fuel_Tank_Capacity (in litres)'].astype(str)

In [96]:

cars['Fuel_Tank_Capacity (in litres)'] = [i.replace('litres','') for i in cars['Fuel_Tank_Capacity (in litres)']]

In [97]:
cars['Fuel_Tank_Capacity (in litres)'] = cars['Fuel_Tank_Capacity (in litres)'].astype(float)

In [101]:
cars['Height (in mm)'] = cars['Height (in mm)'].astype(str)

In [102]:
cars['Height (in mm)'] = [i.replace('mm','') for i in cars['Height (in mm)']]

In [103]:
cars['Height (in mm)'] = cars['Height (in mm)'].astype(float)

In [104]:

cars['Length (in mm)'] = cars['Length (in mm)'].astype(str)

In [106]:

cars['Length (in mm)'] = [i.replace('mm','') for i in cars['Length (in mm)']]

In [107]:

cars['Length (in mm)'] = cars['Length (in mm)'].astype(float)

In [109]:

cars['width (in mm)'] = cars['width (in mm)'].astype(str)

In [114]:



cars['width (in mm)'] = [i.replace('mm','') for i in cars['width (in mm)']]

In [115]:

cars['width (in mm)'] = cars['width (in mm)'].astype(float)

In [116]:
cars['City_Mileage (km/litre)'] = cars['City_Mileage (km/litre)'].astype(str)

In [120]:
cars['City_Mileage (km/litre)'] = [i.replace('km/litre','') for i in cars['City_Mileage (km/litre)']]

In [121]:
cars['City_Mileage (km/litre)'] = [i.replace('?','') for i in cars['City_Mileage (km/litre)']]

In [126]:
cars['City_Mileage (km/litre)'] = [i.replace(',','.') for i in cars['City_Mileage (km/litre)']]

In [129]:
cars['City_Mileage (km/litre)'] = [i.replace('12.5-12.7 ','12.6') for i in cars['City_Mileage (km/litre)']]

In [131]:

cars['City_Mileage (km/litre)'] = cars['City_Mileage (km/litre)'].astype(float)

In [132]:
cars['Highway_Mileage (km/litre)'] = cars['Highway_Mileage (km/litre)'].astype(str)

In [133]:
cars['Highway_Mileage (km/litre)'] = [i.replace('km/litre','') for i in cars['Highway_Mileage (km/litre)']]

In [135]:
cars['Highway_Mileage (km/litre)'] = [i.replace('8.3-8.4 ','8.4') for i in cars['Highway_Mileage (km/litre)']]

In [136]:
cars['Highway_Mileage (km/litre)'] = cars['Highway_Mileage (km/litre)'].astype(float)

In [137]:
cars['ARAI_Certified_Mileage (km/litre)'] = cars['ARAI_Certified_Mileage (km/litre)'].astype(str)

In [138]:
cars['ARAI_Certified_Mileage (km/litre)'] = [i.replace('km/litre','') for i in cars['ARAI_Certified_Mileage (km/litre)']]

In [142]:
cars['ARAI_Certified_Mileage (km/litre)'] = [i.replace('22.4-21.9 ','22.1') for i in cars['ARAI_Certified_Mileage (km/litre)']]

In [144]:
cars['ARAI_Certified_Mileage (km/litre)'] = [i.replace('kmpl ','') for i in cars['ARAI_Certified_Mileage (km/litre)']]

In [145]:
cars['ARAI_Certified_Mileage (km/litre)'] = cars['ARAI_Certified_Mileage (km/litre)'].astype(float)

In [146]:
cars['ARAI_Certified_Mileage_for_CNG (km/kg)'] = cars['ARAI_Certified_Mileage_for_CNG (km/kg)'].astype(str)

In [147]:
cars['ARAI_Certified_Mileage_for_CNG (km/kg)'] = [i.replace('km/kg','') for i in cars['ARAI_Certified_Mileage_for_CNG (km/kg)']]

In [148]:
cars['ARAI_Certified_Mileage_for_CNG (km/kg)'] = cars['ARAI_Certified_Mileage_for_CNG (km/kg)'].astype(float)

In [149]:
cars['Kerb_Weight (kg)'] = cars['Kerb_Weight (kg)'].astype(str)

In [150]:

cars['Kerb_Weight (kg)'] = [i.replace('kg','') for i in cars['Kerb_Weight (kg)']]

In [154]:
cars['Ground_Clearance (in mm)'] = cars['Ground_Clearance (in mm)'].astype(str)

In [155]:
cars['Ground_Clearance (in mm)'] = [i.replace(' mm','') for i in cars['Ground_Clearance (in mm)']]

In [156]:
cars['Ground_Clearance (in mm)'] = cars['Ground_Clearance (in mm)'].astype(float)

In [157]:
cars['Front_Track (in mm)'] = cars['Front_Track (in mm)'].astype(str)

In [158]:

cars['Front_Track (in mm)'] = [i.replace(' mm','') for i in cars['Front_Track (in mm)']]

In [162]:

cars['Front_Track (in mm)'] = [i.replace(' (R13)','') for i in cars['Front_Track (in mm)']]

In [164]:

cars['Front_Track (in mm)'] = [i.replace(',','') for i in cars['Front_Track (in mm)']]

In [165]:
cars['Front_Track (in mm)'] = cars['Front_Track (in mm)'].astype(float)

In [166]:
cars['Rear_Track (in mm)'] = cars['Rear_Track (in mm)'].astype(str)

In [168]:
cars['Rear_Track (in mm)'] = [i.replace(' mm','') for i in cars['Rear_Track (in mm)']]

In [170]:
cars['Rear_Track (in mm)'] = [i.replace(' (R13)','') for i in cars['Rear_Track (in mm)']]
cars['Rear_Track (in mm)'] = [i.replace(',','') for i in cars['Rear_Track (in mm)']]

In [171]:
cars['Rear_Track (in mm)'] = cars['Rear_Track (in mm)'].astype(float)

In [172]:
cars['Wheelbase (in mm)'] = cars['Wheelbase (in mm)'].astype(str)

In [173]:
cars['Wheelbase (in mm)'] = [i.replace(' mm','') for i in cars['Wheelbase (in mm)']]

In [174]:
cars['Wheelbase (in mm)'] = cars['Wheelbase (in mm)'].astype(float)

In [175]:
cars['Boot_Space (in litres)'] = cars['Boot_Space (in litres)'].astype(str)

In [181]:
cars['Boot_Space (in litres)'] = [i.replace('209(All3RowsUp).550(3rdRowFolded)&803(2ndRowand3rdRowFolded)','209') for i in cars['Boot_Space (in litres)']]

In [182]:
cars['Boot_Space (in litres)'] = cars['Boot_Space (in litres)'].astype(float)

## Missing values DataFrame

In [197]:
missing_val = pd.DataFrame(round(cars.isna().sum()/cars.isna().count()*100,2), columns = ['missing values'])

In [253]:

missing_val[missing_val['missing values'] > 50]

                                        missing values
Highway_Mileage (km/litre)                       62.70
ARAI_Certified_Mileage_for_CNG (km/kg)           97.88
Front_Track (in mm)                              52.27
Rear_Track (in mm)                               52.98
Power_Seats                                      69.98
Start_/_Stop_Button                              53.13
Extended_Warranty                                51.80
Hill_Assist                                      62.38
3_Point_Seat-Belt_in_Middle_Rear_Seat            96.00
Ambient_Lightning                                95.61
Cargo/Boot_Lights                                90.52
Drive_Modes                                      84.72
High_Speed_Alert_System                          83.70
Lane_Watch_Camera/_Side_Mirror_Camera            94.83
Passenger_Side_Seat-Belt_Reminder                86.60
Voice_Recognition                                89.66
Walk_Away_Auto_Car_Lock                          91.93
Compression_Ratio                                71.87
Other_Specs                                      99.22
Other_specs                                      95.06
Android_Auto                                     86.44
Apple_CarPlay                                    86.44
Cigarette_Lighter                                53.45
EBA_(Electronic_Brake_Assist)                    54.08
Tyre_Pressure_Monitoring_System                  73.35
iPod_Compatibility                               51.96
ESP_(Electronic_Stability_Program)               61.05
Cooled_Glove_Box                                 50.55
Recommended_Tyre_Pressure                        99.22
Heated_Seats                                     79.15
ISOFIX_(Child-Seat_Mount)                        52.19
Rain_Sensing_Wipers                              62.54
Paddle_Shifters                                  76.18
Leather_Wrapped_Steering                         54.00
Automatic_Headlamps                              60.66
Engine_Type                                      97.34
ASR_/_Traction_Control                           65.36
Cruise_Control                                   56.97
USB_Ports                                        97.73
Heads-Up_Display                                 96.00
Welcome_Lights                                   94.59
Battery                                          98.98
Electric_Range                                   98.67

In [257]:
missing_val[20:40]

                                        missing values
Highway_Mileage (km/litre)                       62.70
ARAI_Certified_Mileage (km/litre)                 8.93
ARAI_Certified_Mileage_for_CNG (km/kg)           97.88
Kerb_Weight (kg)                                  0.00
Gears                                             8.23
Ground_Clearance (in mm)                         22.65
Front_Brakes                                      1.96
Rear_Brakes                                       1.96
Front_Suspension                                  4.62
Rear_Suspension                                   3.61
Front_Track (in mm)                              52.27
Rear_Track (in mm)                               52.98
Front_Tyre_&_Rim                                  3.84
Rear_Tyre_&_Rim                                   3.76
Power_Steering                                    4.47
Power_Windows                                     7.60
Power_Seats                                      69.98
Keyless_Entry                                    21.47
Power                                             0.00
Torque                                            0.16

## Filling empty 'Make' column values

In [213]:
cars.loc[cars['Make'].isna() , 'Make'] = [i.split(' ')[0] for i in cars[cars['Make'].isna()]['Model']]

In [216]:

cars[cars['Displacement (in cc)'].isna()]

,Make,Model,Variant,Ex-Showroom_Price (in Rs.),Displacement (in cc),Cylinders,Valves_Per_Cylinder,Drivetrain,Cylinder_Configuration,Emission_Norm,...,Leather_Wrapped_Steering,Automatic_Headlamps,Engine_Type,ASR_/_Traction_Control,Cruise_Control,USB_Ports,Heads-Up_Display,Welcome_Lights,Battery,Electric_Range
615,Mahindra,E2O Plus,P4,881425,NaN,NaN,NaN,RWD (Rear Wheel Drive),In-line,BS IV,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,210 ampere-hour,110 km/full charge
616,Mahindra,E2O Plus,P6,957177,NaN,NaN,NaN,RWD (Rear Wheel Drive),In-line,BS IV,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,210 ampere-hour,110 km/full charge
617,Tata,Tigor Ev,Xm+,960868,NaN,NaN,NaN,FWD (Front Wheel Drive),NaN,BS VI,...,NaN,NaN,M1 Category,NaN,NaN,NaN,NaN,NaN,"21.5 kWh,Battery Placed Under Rear Seats",213 km/full charge
618,Tata,Tigor Ev,Xt+,975868,NaN,NaN,NaN,FWD (Front Wheel Drive),NaN,BS VI,...,NaN,NaN,M1 Category,NaN,NaN,NaN,NaN,NaN,"21.5 kWh,Battery Placed Under Rear Seats",213 km/full charge
619,Tata,Tigor Ev,Xe+,944175,NaN,NaN,NaN,FWD (Front Wheel Drive),NaN,BS VI,...,NaN,NaN,M1 Category,NaN,NaN,NaN,NaN,NaN,"21.5 kWh,Battery Placed Under Rear Seats",213 km/full charge
745,Mg,Zs Ev,Excite,2088000,NaN,NaN,NaN,RWD (Rear Wheel Drive),In-line,BS 6,...,Yes,Yes,NaN,Yes,Yes,NaN,Yes,NaN,"44.5 (kWh), Lithium Ion",340 km/full charge
746,Mg,Zs Ev,Exclusive,2358000,NaN,NaN,NaN,RWD (Rear Wheel Drive),In-line,BS 6,...,Yes,Yes,NaN,Yes,Yes,NaN,Yes,NaN,"44.5 (kWh), Lithium Ion",340 km/full charge
862,Mercedes-Benz,Mercedes-Benz Amg Gt 4-Door Coupe,63 S 4Matic+,24200000,NaN,8.0,6.0,AWD (All Wheel Drive),V,BS 6,...,NaN,NaN,Biturbo engine,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1006,Tata,Nexon Ev,Xm,1399000,NaN,NaN,NaN,FWD (Front Wheel Drive),In-line,BS VI,...,NaN,NaN,NaN,Yes,NaN,NaN,Yes,NaN,"30.2 kWh* Advanced Li-ion polymer, liquid cool...",312 km/full charge
1007,Tata,Nexon Ev,Xz Plus,1499000,NaN,NaN,NaN,FWD (Front Wheel Drive),In-line,BS VI,...,NaN,NaN,NaN,Yes,NaN,NaN,Yes,NaN,"30.2 kWh* Advanced Li-ion polymer, liquid cool...",312 km/full charge
1008,Tata,Nexon Ev,Xz Plus Lux,1599000,NaN,NaN,NaN,FWD (Front Wheel Drive),In-line,BS VI,...,NaN,Yes,NaN,Yes,NaN,NaN,Yes,NaN,"30.2 kWh* Advanced Li-ion polymer, liquid cool...",300 km/full charge
1205,Hyundai,Kona Electric,Premium,2371858,NaN,NaN,NaN,FWD (Front Wheel Drive),NaN,NaN,...,Yes,Yes,NaN,NaN,Yes,NaN,NaN,Yes,NaN,462 km/full charge

## Exporting data

In [221]:
cars.to_csv('cars_cleaned.csv')

In [229]:
cars.columns

Index(['Make', 'Model', 'Variant', 'Ex-Showroom_Price (in Rs.)',
       'Displacement (in cc)', 'Cylinders', 'Valves_Per_Cylinder',
       'Drivetrain', 'Cylinder_Configuration', 'Emission_Norm',
       ...
       'Leather_Wrapped_Steering', 'Automatic_Headlamps', 'Engine_Type',
       'ASR_/_Traction_Control', 'Cruise_Control', 'USB_Ports',
       'Heads-Up_Display', 'Welcome_Lights', 'Battery', 'Electric_Range'],
      dtype='object', length=140)

In [235]:
cars[cars['City_Mileage (km/litre)'] < 6]

,Make,Model,Variant,Ex-Showroom_Price (in Rs.),Displacement (in cc),Cylinders,Valves_Per_Cylinder,Drivetrain,Cylinder_Configuration,Emission_Norm,...,Leather_Wrapped_Steering,Automatic_Headlamps,Engine_Type,ASR_/_Traction_Control,Cruise_Control,USB_Ports,Heads-Up_Display,Welcome_Lights,Battery,Electric_Range
280,Jaguar,Xf,2.0 Prestige,5436329,1999.0,4.0,4.0,RWD (Rear Wheel Drive),V,BS IV,...,Yes,Yes,NaN,Yes,Yes,NaN,NaN,NaN,NaN,NaN
281,Jaguar,Xf,2.0 Portfolio,6073446,1999.0,4.0,4.0,RWD (Rear Wheel Drive),V,BS IV,...,Yes,Yes,NaN,Yes,Yes,NaN,NaN,NaN,NaN,NaN
282,Jaguar,Xf,2.0 Portfolio Diesel,6138811,1999.0,4.0,4.0,RWD (Rear Wheel Drive),V,BS IV,...,Yes,Yes,NaN,Yes,Yes,NaN,NaN,NaN,NaN,NaN
283,Jaguar,Xf,2.0 Prestige Diesel,5506622,1999.0,4.0,4.0,RWD (Rear Wheel Drive),V,BS IV,...,Yes,Yes,NaN,Yes,Yes,NaN,NaN,NaN,NaN,NaN
284,Jaguar,Xf,2.0 Pure Diesel,4977080,1999.0,4.0,4.0,RWD (Rear Wheel Drive),V,BS IV,...,Yes,Yes,NaN,Yes,Yes,NaN,NaN,NaN,NaN,NaN
303,Mercedes-Benz,Mercedes-Benz E-Class Cabriolet,E400,7711338,2996.0,6.0,4.0,NaN,V,BS IV,...,NaN,Yes,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN
323,Mercedes-Benz,Mercedes-Benz S-Class,S 450,13976653,2996.0,6.0,4.0,RWD (Rear Wheel Drive),V,BS IV,...,Yes,Yes,NaN,Yes,Yes,NaN,NaN,NaN,NaN,NaN
324,Mercedes-Benz,Mercedes-Benz S-Class,Amg S 63 Coupe,25500000,3982.0,8.0,4.0,AWD (All Wheel Drive),V,BS IV,...,Yes,Yes,NaN,Yes,Yes,NaN,NaN,NaN,NaN,NaN
325,Maserati,Levante,Diesel,14512054,2987.0,6.0,4.0,AWD (All Wheel Drive),V,BS IV,...,Yes,Yes,NaN,Yes,Yes,NaN,NaN,NaN,NaN,NaN
326,Maserati,Levante,Gransport,14863774,2979.0,6.0,4.0,AWD (All Wheel Drive),V,BS IV,...,Yes,Yes,NaN,Yes,Yes,NaN,NaN,NaN,NaN,NaN
327,Maserati,Levante,Granlusson,15383399,2979.0,6.0,4.0,AWD (All Wheel Drive),V,BS IV,...,Yes,Yes,NaN,Yes,Yes,NaN,NaN,NaN,NaN,NaN
331,Maserati,Granturismo,Sport,17229579,4691.0,8.0,4.0,RWD (Rear Wheel Drive),V,BS IV,...,Yes,Yes,NaN,Yes,Yes,NaN,NaN,NaN,NaN,NaN
332,Maserati,Quattroporte,Granlusso,17900000,2987.0,6.0,4.0,RWD (Rear Wheel Drive),V,BS 6,...,Yes,Yes,NaN,Yes,Yes,NaN,NaN,NaN,NaN,NaN
340,Mercedes-Benz,Mercedes-Benz S-Class Cabriolet,S500,23491293,4663.0,8.0,4.0,RWD (Rear Wheel Drive),V,BS IV,...,Yes,Yes,NaN,Yes,Yes,NaN,NaN,NaN,NaN,NaN
343,Bentley,Continental Gt,Coupe,33791059,5998.0,12.0,4.0,AWD (All Wheel Drive),W,BS IV,...,Yes,Yes,NaN,Yes,Yes,NaN,NaN,NaN,NaN,NaN
351,Rolls-Royce,Rolls-Royce Wraith,Coupe,50025840,6592.0,12.0,4.0,AWD (All Wheel Drive),V,BS IV,...,NaN,Yes,NaN,Yes,Yes,NaN,NaN,NaN,NaN,NaN
796,Mercedes-Benz,Mercedes-Benz E-Class,E 63 S Amg,15000000,5461.0,8.0,4.0,AWD (All Wheel Drive),V,BS IV,...,Yes,Yes,NaN,Yes,Yes,NaN,NaN,NaN,NaN,NaN
824,Volvo,Xc90,T8 Excellence,13124000,1969.0,4.0,4.0,AWD (All Wheel Drive),In-line,BS IV,...,Yes,Yes,NaN,Yes,Yes,NaN,NaN,NaN,NaN,NaN
836,Land Rover Rover,Range Sport,4.4L Sdv8 Hse Diesel,14908985,4367.0,8.0,2.0,4WD,V,BS IV,...,Yes,Yes,NaN,Yes,Yes,NaN,NaN,NaN,NaN,NaN
846,Toyota,Land Cruiser,Vx,14699000,4461.0,8.0,4.0,AWD (All Wheel Drive),V,BS IV,...,Yes,Yes,NaN,Yes,Yes,NaN,NaN,NaN,NaN,NaN
847,Audi,Rs7,Sportback,17072000,3993.0,8.0,4.0,AWD (All Wheel Drive),In-line,BS IV,...,Yes,Yes,NaN,Yes,Yes,NaN,NaN,NaN,NaN,NaN
848,Land Rover Rover,Range,5.0L V8 Autobiography Petrol,26037526,4999.0,8.0,4.0,4WD,V,BS IV,...,Yes,Yes,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN
849,Land Rover Rover,Range,5.0L V8 Svautobiography Dynamic Petrol,32522000,4999.0,8.0,2.0,4WD,V,BS IV,...,Yes,Yes,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN
858,Maserati,Grancabrio,Standard,19865675,4691.0,8.0,4.0,RWD (Rear Wheel Drive),V,BS IV,...,Yes,Yes,NaN,Yes,Yes,NaN,NaN,NaN,NaN,NaN
859,Mercedes-Benz,Mercedes-Benz Amg-Gt,S,21583466,3982.0,8.0,4.0,AWD (All Wheel Drive),V,BS IV,...,Yes,Yes,NaN,Yes,Yes,NaN,NaN,NaN,NaN,NaN
860,Mercedes-Benz,Mercedes-Benz Amg-Gt,R,23264134,3982.0,8.0,4.0,AWD (All Wheel Drive),V,BS IV,...,Yes,Yes,NaN,Yes,Yes,NaN,NaN,NaN,NaN,NaN
861,Mercedes-Benz,Mercedes-Benz Amg-Gt,Roadster,22733626,3982.0,8.0,4.0,AWD (All Wheel Drive),V,BS IV,...,Yes,Yes,NaN,Yes,Yes,NaN,NaN,NaN,NaN,NaN
863,Lamborghini,Huracan,Lp 610-4,37133704,5204.0,10.0,4.0,AWD (All Wheel Drive),V,BS IV,...,Yes,Yes,NaN,Yes,Yes,NaN,NaN,NaN,NaN,NaN
864,Lamborghini,Huracan,Lp 580-2,32452486,5204.0,10.0,4.0,RWD (Rear Wheel Drive),V,BS IV,...,Yes,Yes,NaN,Yes,Yes,NaN,NaN,NaN,NaN,NaN
866,Lamborghini,Huracan,Performante,37614126,5204.0,10.0,4.0,AWD (All Wheel Drive),V,BS IV,...,Yes,Yes,NaN,Yes,Yes,NaN,NaN,NaN,NaN,NaN
867,Lamborghini,Huracan,Lp 580-2 Spyder,35535000,5204.0,10.0,4.0,RWD (Rear Wheel Drive),V,BS IV,...,Yes,Yes,NaN,Yes,Yes,NaN,NaN,NaN,NaN,NaN
868,Lamborghini,Huracan,Lp 610-4 Spyder,40742932,5204.0,10.0,4.0,AWD (All Wheel Drive),V,BS IV,...,Yes,Yes,NaN,Yes,Yes,NaN,NaN,NaN,NaN,NaN
869,Lamborghini,Huracan,Evo,37300000,5204.0,10.0,4.0,AWD (All Wheel Drive),V,BS IV,...,Yes,Yes,NaN,Yes,Yes,NaN,NaN,NaN,NaN,NaN
870,Lamborghini,Huracan,Evo Spyder,41000000,5204.0,10.0,4.0,AWD (All Wheel Drive),V,BS IV,...,Yes,Yes,NaN,Yes,Yes,NaN,NaN,NaN,NaN,NaN
871,Lamborghini,Huracan,Evo Rwd,32200000,5204.0,10.0,4.0,RWD (Rear Wheel Drive),V,BS 6,...,Yes,Yes,NaN,Yes,Yes,NaN,NaN,NaN,NaN,NaN
872,Ferrari,488 Gtb,Std,36761413,3902.0,8.0,4.0,AWD (All Wheel Drive),V,BS IV,...,Yes,Yes,NaN,Yes,Yes,NaN,NaN,NaN,NaN,NaN
873,Ferrari,488 Gtb,Spider,39319552,3902.0,8.0,4.0,AWD (All Wheel Drive),V,BS IV,...,Yes,Yes,NaN,Yes,Yes,NaN,NaN,NaN,NaN,NaN
876,Lamborghini,Aventador,Lp 700-4,47893943,6498.0,12.0,4.0,4WD,V,BS IV,...,Yes,Yes,NaN,Yes,Yes,NaN,NaN,NaN,NaN,NaN
877,Lamborghini,Aventador,Lp700-4 Roadster,53210327,6498.0,12.0,4.0,4WD,V,BS IV,...,Yes,Yes,NaN,Yes,Yes,NaN,NaN,NaN,NaN,NaN
878,Lamborghini,Aventador,S,47467700,6498.0,12.0,4.0,4WD,V,BS IV,...,Yes,Yes,NaN,Yes,Yes,NaN,NaN,NaN,NaN,NaN
880,Rolls-Royce,Rolls-Royce Drophead Coupe,Phantom,83755383,6749.0,12.0,4.0,RWD (Rear Wheel Drive),V,BS IV,...,Yes,Yes,NaN,Yes,Yes,NaN,NaN,NaN,NaN,NaN
1056,Aston Martin,Vantage,Coupe,29500000,3982.0,8.0,4.0,RWD (Rear Wheel Drive),V,BS IV,...,Yes,Yes,NaN,Yes,Yes,NaN,NaN,NaN,NaN,NaN
1158,Bmw,6-Series,630I Gt Luxury Line,6440000,4395.0,8.0,4.0,RWD (Rear Wheel Drive),In-line,BS IV,...,Yes,Yes,NaN,Yes,Yes,NaN,NaN,NaN,NaN,NaN
1172,Ferrari,458 Spider,V8,43367500,3902.0,8.0,4.0,AWD (All Wheel Drive),V,BS IV,...,Yes,Yes,NaN,Yes,Yes,NaN,NaN,NaN,NaN,NaN
1263,Bentley,Flying Spur,V8,34167064,3993.0,8.0,4.0,AWD (All Wheel Drive),V,BS IV,...,Yes,Yes,NaN,Yes,Yes,NaN,NaN,NaN,NaN,NaN
1264,Bentley,Flying Spur,W12,39382083,5998.0,12.0,4.0,AWD (All Wheel Drive),W,BS IV,...,Yes,Yes,NaN,Yes,Yes,NaN,NaN,NaN,NaN,NaN

In [234]:
cars[(cars['City_Mileage (km/litre)'] > 14) & (cars['City_Mileage (km/litre)'] < 20)]

,Make,Model,Variant,Ex-Showroom_Price (in Rs.),Displacement (in cc),Cylinders,Valves_Per_Cylinder,Drivetrain,Cylinder_Configuration,Emission_Norm,...,Leather_Wrapped_Steering,Automatic_Headlamps,Engine_Type,ASR_/_Traction_Control,Cruise_Control,USB_Ports,Heads-Up_Display,Welcome_Lights,Battery,Electric_Range
31,Maruti Suzuki,Alto K10,Lx,360843,998.0,3.0,4.0,FWD (Front Wheel Drive),In-line,BS IV,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75,Maruti Suzuki,Ignis,Zeta 1.2 Amt,630320,1197.0,4.0,4.0,FWD (Front Wheel Drive),In-line,BS IV,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
87,Toyota,Etios Liva,G,520300,1197.0,4.0,4.0,FWD (Front Wheel Drive),In-line,BS IV,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88,Toyota,Etios Liva,V,581000,1197.0,4.0,4.0,FWD (Front Wheel Drive),In-line,BS IV,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90,Toyota,Etios Liva,Vx,630000,1197.0,4.0,4.0,FWD (Front Wheel Drive),In-line,BS IV,...,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1266,Honda,City,V Mt Petrol,1065900,1497.0,4.0,4.0,FWD (Front Wheel Drive),In-line,BS 6,...,NaN,NaN,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN
1267,Honda,City,Vx Mt Petrol,1182000,1497.0,4.0,4.0,FWD (Front Wheel Drive),In-line,BS 6,...,Yes,NaN,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN
1268,Honda,City,Vx Cvt Petrol,1312000,1497.0,4.0,4.0,FWD (Front Wheel Drive),In-line,BS 6,...,Yes,NaN,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN
1273,Honda,City,Zx Cvt Petrol,1431000,1497.0,4.0,4.0,FWD (Front Wheel Drive),In-line,BS 6,...,Yes,Yes,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN
1274,Honda,City,V Cvt Petrol,1201000,1497.0,4.0,4.0,FWD (Front Wheel Drive),In-line,BS 6,...,NaN,NaN,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN

In [226]:
cars[cars['Ex-Showroom_Price (in Rs.)'] > 10000000]

,Make,Model,Variant,Ex-Showroom_Price (in Rs.),Displacement (in cc),Cylinders,Valves_Per_Cylinder,Drivetrain,Cylinder_Configuration,Emission_Norm,...,Leather_Wrapped_Steering,Automatic_Headlamps,Engine_Type,ASR_/_Traction_Control,Cruise_Control,USB_Ports,Heads-Up_Display,Welcome_Lights,Battery,Electric_Range
301,Jeep,Grand Cherokee,Srt,11400000,6417.0,8.0,4.0,AWD (All Wheel Drive),V,BS IV,...,NaN,Yes,NaN,Yes,Yes,NaN,NaN,NaN,NaN,NaN
308,Mercedes-Benz,Mercedes-Benz Gls,63 Amg,19199181,5461.0,8.0,4.0,AWD (All Wheel Drive),V,BS IV,...,Yes,NaN,NaN,Yes,Yes,NaN,NaN,NaN,NaN,NaN
314,Audi,Rs5,Coupe,11141200,2894.0,8.0,4.0,AWD (All Wheel Drive),In-line,BS IV,...,Yes,Yes,NaN,Yes,Yes,NaN,NaN,NaN,NaN,NaN
315,Bmw,7-Series,730Ld Design Pure Excellence,12290000,2993.0,6.0,4.0,AWD (All Wheel Drive),V,BS 6,...,Yes,Yes,NaN,Yes,Yes,NaN,Yes,Yes,NaN,NaN
316,Bmw,7-Series,730Ld Design Pure Excellence Signature,13200000,2993.0,6.0,4.0,AWD (All Wheel Drive),V,BS 6,...,Yes,Yes,NaN,Yes,Yes,3.0,Yes,Yes,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1220,Rolls-Royce,Rolls-Royce Phantom,Ewb,75400000,6749.0,12.0,4.0,RWD (Rear Wheel Drive),V,BS IV,...,Yes,Yes,NaN,Yes,Yes,NaN,NaN,NaN,NaN,NaN
1253,Porsche,Cayenne Coupe,Base,13151000,2995.0,6.0,4.0,AWD (All Wheel Drive),V,BS 6,...,Yes,Yes,NaN,Yes,Yes,NaN,Yes,Yes,NaN,NaN
1254,Porsche,Cayenne Coupe,Turbo,19763000,2995.0,8.0,4.0,AWD (All Wheel Drive),V,BS 6,...,Yes,Yes,NaN,Yes,Yes,NaN,Yes,Yes,NaN,NaN
1263,Bentley,Flying Spur,V8,34167064,3993.0,8.0,4.0,AWD (All Wheel Drive),V,BS IV,...,Yes,Yes,NaN,Yes,Yes,NaN,NaN,NaN,NaN,NaN
1264,Bentley,Flying Spur,W12,39382083,5998.0,12.0,4.0,AWD (All Wheel Drive),W,BS IV,...,Yes,Yes,NaN,Yes,Yes,NaN,NaN,NaN,NaN,NaN

In [236]:
cars['City_Mileage (km/litre)'].isna().sum()

555

In [240]:
missing_val[18:27]

                                        missing values
Doors                                             0.31
City_Mileage (km/litre)                          43.50
Highway_Mileage (km/litre)                       62.70
ARAI_Certified_Mileage (km/litre)                 8.93
ARAI_Certified_Mileage_for_CNG (km/kg)           97.88
Kerb_Weight (kg)                                  0.00
Gears                                             8.23
Ground_Clearance (in mm)                         22.65
Front_Brakes                                      1.96

In [241]:
cars[['City_Mileage (km/litre)' , 'ARAI_Certified_Mileage (km/litre)']]

      City_Mileage (km/litre)  ARAI_Certified_Mileage (km/litre)
0                       23.60                              23.60
1                       23.60                              23.60
2                         NaN                                NaN
3                       23.60                              21.90
4                       23.60                              23.60
...                       ...                                ...
1271                    22.60                              25.10
1272                    22.60                              25.10
1273                    18.00                              22.60
1274                    14.30                              17.80
1275                     8.25                              11.56

[1276 rows x 2 columns]

In [243]:
missing val

SyntaxError: invalid syntax (Temp/ipykernel_10992/1866365539.py, line 1)

In [247]:
missing_val[missing_val['missing values']

(70, 1)

In [252]:
[i for i in cars['Ex-Showroom_Price (in Rs.)']]

[292667,
 236447,
 296661,
 334768,
 272223,
 314815,
 279650,
 351832,
 333419,
 362000,
 390000,
 437065,
 353290,
 283290,
 383290,
 413290,
 433290,
 454490,
 463290,
 484490,
 440990,
 470990,
 462190,
 492190,
 352136,
 380573,
 392967,
 466057,
 425255,
 377588,
 394036,
 360843,
 407238,
 439777,
 438559,
 374990,
 468229,
 502492,
 499990,
 469990,
 528464,
 553015,
 594464,
 618015,
 422444,
 480670,
 429990,
 503990,
 547990,
 530990,
 512990,
 578990,
 570990,
 556490,
 460000,
 520000,
 570000,
 599000,
 610000,
 620000,
 649000,
 660000,
 481074,
 475198,
 518198,
 524074,
 499734,
 540350,
 542735,
 552350,
 713898,
 666898,
 607841,
 560841,
 483320,
 630320,
 583320,
 495000,
 559000,
 609000,
 663000,
 506000,
 568623,
 670000,
 603000,
 739000,
 739000,
 520300,
 581000,
 647800,
 630000,
 745000,
 704000,
 597700,
 720700,
 641700,
 756700,
 558400,
 686000,
 662700,
 777700,
 525021,
 599950,
 563133,
 787980,
 661111,
 693798,
 719661,
 674960,
 529035,
 590268,
 614515,
 556130,
 536859,
 556130,
 536859,
 639616,
 620297,
 653523,
 553423,
 598940,
 559693,
 697803,
 634950,
 770803,
 721693,
 876103,
 808993,
 934003,
 920993,
 751693,
 831693,
 846103,
 579900,
 655900,
 705800,
 729900,
 804800,
 785900,
 728900,
 854900,
 773800,
 823700,
 922700,
 903800,
 582000,
 676500,
 776500,
 734500,
 851500,
 931500,
 976000,
 988500,
 582613,
 673112,
 666622,
 732113,
 757622,
 720112,
 863122,
 816622,
 821613,
 779113,
 868613,
 906122,
 804622,
 952622,
 676400,
 790900,
 836400,
 591400,
 721400,
 756400,
 681400,
 745900,
 711500,
 810500,
 999900,
 925500,
 594000,
 665000,
 799900,
 999900,
 598500,
 697400,
 663400,
 699400,
 737400,
 777400,
 817400,
 862400,
 782400,
 737400,
 758314,
 762400,
 842400,
 627100,
 718600,
 734700,
 828600,
 888400,
 778400,
 689600,
 799600,
 913400,
 803400,
 802000,
 650000,
 797500,
 766000,
 668500,
 816000,
 657628,
 685729,
 750428,
 677618,
 739074,
 977516,
 810211,
 721900,
 758200,
 829900,
 890200,
 697900,
 796132,
 711801,
 876341,
 745000,
 909000,
 789000,
 865000,
 816500,
 896500,
 940500,
 928000,
 2680000,
 2760000,
 2734834,
 2931534,
 2770150,
 3070150,
 2814500,
 3153500,
 2827001,
 3067001,
 3277001,
 2899599,
 3149599,
 3021200,
 3221200,
 2920750,
 3120750,
 2988311,
 3089851,
 3198662,
 3303282,
 3599000,
 3172000,
 3699000,
 3299599,
 3678599,
 3299599,
 3407407,
 3677200,
 3992200,
 4361000,
 3496750,
 3600000,
 3830000,
 3990000,
 4390000,
 3990000,
 4120000,
 4149000,
 4507000,
 4350000,
 4498000,
 4498000,
 4633000,
 4633000,
 5436329,
 6073446,
 6138811,
 5506622,
 4977080,
 5038000,
 5442200,
 5942200,
 5930000,
 5880000,
 5600000,
 5706000,
 6089000,
 5890000,
 7243000,
 7330000,
 8290000,
 8290000,
 7462000,
 7882867,
 8931819,
 11400000,
 7515000,
 7711338,
 8180000,
 8995000,
 8595000,
 8820000,
 19199181,
 8776900,
 8690000,
 8690000,
 9630000,
 9900000,
 11141200,
 12290000,
 13200000,
 13510000,
 13510000,
 16500000,
 24250000,
 13359500,
 13558438,
 13976653,
 25500000,
 14512054,
 14863774,
 15383399,
 21875136,
 15000000,
 15600000,
 17229579,
 17900000,
 19600000,
 27308312,
 19890000,
 21263000,
 22613000,
 21747000,
 23290000,
 23491293,
 27245000,
 30000000,
 33791059,
 35000000,
 45941557,
 37542069,
 40456503,
 42531500,
 46709733,
 53247201,
 50025840,
 52571294,
 69500000,
 77312661,
 192142937,
 212155397,
 263000,
 283000,
 294800,
 299900,
 352900,
 357200,
 376100,
 405570,
 409190,
 389600,
 370500,
 376500,
 409000,
 415000,
 432500,
 438500,
 475500,
 456000,
 481500,
 499000,
 426289,
 465138,
 508138,
 490924,
 531279,
 530000,
 533924,
 434659,
 472257,
 515257,
 543279,
 551530,
 568930,
 460369,
 477511,
 545946,
 528804,
 488194,
 532184,
 590798,
 619243,
 667273,
 579645,
 631144,
 754548,
 693550,
 787304,
 701045,
 794800,
 573250,
 631146,
 687175,
 660832,
 748128,
 780884,
 550155,
 559741,
 524312,
 542913,
 519000,
 619000,
 666000,
 678000,
 725000,
 758000,
 599000,
 698000,
 745000,
 757000,
 804000,
 838000,
 802000,
 884000,
 529000,
 615000,
 684000,
 744000,
 769000,
 699000,
 775000,
 844000,
 904000,
 929000,
 642478,
 589678,
 689761,
 788177,
 2650777,
 628072,
 900967,
 1465148,
 552890,
 927689,
 835275,
 575000,
 610000,
 650000,
 699000,
 660000,
 749000,
 582287,
 702946,
 653926,
 672641,
 732475,
 767317,
 793898,
 855362,
 836320,
 989000,
 788797,
 763000,
 705000,
 593000,
 865000,
 823000,
 925000,
 785000,
 893000,
 845000,
 781000,
 733000,
 673000,
 906000,
 794000,
 966000,
 864000,
 979300,
 877300,
 906300,
 794300,
 637343,
 622730,
 655000,
 826000,
 780000,
 959000,
 974000,
 1065000,
 940000,
 1115500,
 725000,
 850000,
 983000,
 998000,
 1089000,
 695000,
 770000,
 870000,
 950000,
 970000,
 1040000,
 1060000,
 830000,
 1010000,
 1030000,
 1100000,
 1120000,
 845000,
 920000,
 1020000,
 1100000,
 1120000,
 1190000,
 1210000,
 980000,
 1160000,
 1180000,
 1250000,
 1270000,
 715860,
 862175,
 932025,
 991434,
 997763,
 886398,
 851302,
 785656,
 749192,
 859497,
 819117,
 762742,
 814742,
 892243,
 987743,
 1003552,
 1037742,
 864742,
 942243,
 1059742,
 774035,
 858536,
 882298,
 993393,
 791000,
 871000,
 950000,
 1130000,
 841000,
 921000,
 999900,
 1090000,
 999900,
 1145000,
 999900,
 1090000,
 799990,
 919990,
 999990,
 929990,
 999990,
 1119990,
 1209990,
 1249990,
 1249990,
 999900,
 1172544,
 1301881,
 1172999,
 1328545,
 1287999,
 933182,
 817867,
 1178894,
 1162875,
 1407871,
 942867,
 999900,
 830127,
 915128,
 1060129,
 1184129,
 869131,
 950131,
 1095129,
 1214130,
 1149800,
 1269131,
 999000,
 863299,
 964199,
 1211599,
 1211599,
 1053899,
 1130099,
 964199,
 876500,
 999900,
 999900,
 1197500,
 1449500,
 958500,
 999900,
 1210500,
 1336500,
 1317500,
 1449500,
 1317500,
 881425,
 957177,
 960868,
 975868,
 944175,
 952900,
 1052900,
 1167900,
 1271900,
 1285900,
 1187900,
 1273900,
 1382900,
 959860,
 999148,
 974860,
 999000,
 1075000,
 1299000,
 1330000,
 975000,
 1225000,
 984689,
 1041189,
 1094689,
 1151189,
 989219,
 992748,
 1029650,
 1142157,
 999900,
 1156471,
 1308592,
 1468440,
 999900,
 1164569,
 1316690,
 1476538,
 999994,
 1236258,
 1123158,
 1220030,
 1330006,
 1360668,
 1540081,
 1663054,
 1423710,
 1425599,
 1269599,
 1299599,
 1139599,
 1610180,
 1418313,
 1539488,
 1588943,
 1710118,
 1716319,
 1837586,
 1741319,
 1862586,
 1610180,
 1418313,
 1539488,
 1588943,
 1710118,
 1716319,
 1837586,
 1741319,
 1862586,
 1852488,
 1973664,
 1230924,
 1293214,
 1267208,
 1303241,
 1639374,
 1929417,
 1912593,
 1796458,
 1371864,
 1531377,
 1655587,
 1605000,
 1927000,
 1610000,
 1932000,
 2113000,
 1620000,
 1615000,
 2103000,
 1807000,
 1493000,
 1498000,
 2097000,
 1892000,
 2171000,
 1592000,
 1587000,
 1996000,
 1560000,
 2055000,
 1661000,
 1803000,
 1888000,
 1973000,
 2022000,
 2151000,
 2199000,
 2167000,
 2133000,
 2311000,
 1699000,
 1599000,
 1900000,
 2070000,
 2036300,
 2214000,
 2499000,
 2196000,
 1645000,
 1806000,
 1882000,
 1936000,
 1771000,
 2019000,
 1793900,
 1944900,
 2124900,
 2054900,
 2234900,
 2088000,
 2358000,
 2495000,
 2515000,
 2895000,
 2995000,
 3395000,
 2599599,
 2779599,
 3099599,
 3349599,
 3029599,
 2599599,
 2849599,
 2769000,
 3191000,
 3205000,
 3019000,
 3216000,
 3395000,
 2977000,
 2818000,
 3420000,
 3470000,
 3233000,
 2920000,
 2990000,
 3420000,
 3399000,
 3520000,
 3930000,
 4570000,
 4240000,
 3830000,
 5602000,
 3850500,
 4140000,
 4690000,
 4790000,
 4426500,
 5021200,
 5621200,
 5021200,
 5621200,
 5494000,
 5985000,
 5494000,
 5985000,
 5861062,
 7285332,
 5964321,
 15000000,
 5750000,
 6150000,
 5850000,
 6250000,
 5990000,
 6060000,
 6590000,
 6350000,
 6394000,
 6426497,
 6490000,
 7890000,
 6840000,
 8190000,
 11000000,
 7221500,
 8021500,
 6921500,
 7621500,
 8111500,
 7711500,
 6952964,
 7246802,
 7246802,
 7500000,
 8790000,
 8090000,
 13124000,
 9665000,
 8491500,
 20517853,
 8670586,
 9448181,
 11476911,
 15600000,
 13228725,
 17940227,
 10373732,
 11913021,
 14908985,
 9738609,
 10725145,
 11129599,
 15806000,
 19210000,
 11936000,
 13387856,
 13881858,
 14247814,
 14699000,
 17072000,
 26037526,
 32522000,
 19527130,
 40499548,
 18185267,
 19527130,
 25174051,
 39294685,
 23675691,
 21398758,
 19865675,
 21583466,
 23264134,
 22733626,
 24200000,
 37133704,
 32452486,
 35150732,
 37614126,
 35535000,
 40742932,
 37300000,
 41000000,
 32200000,
 36761413,
 39319552,
 42000000,
 52000000,
 47893943,
 53210327,
 47467700,
 59216193,
 83755383,
 282778,
 284485,
 412292,
 552656,
 574448,
 555196,
 500575,
 593361,
 615153,
 658361,
 680153,
 482330,
 575947,
 523000,
 623000,
 599900,
 699900,
 664900,
 764900,
 746621,
 868221,
 668611,
 807921,
 758212,
 890212,
 636612,
 768612,
 558602,
 697912,
 733412,
 789912,
 829912,
 586428,
 620637,
 652328,
 705538,
 640537,
 653452,
 751203,
 646336,
 808558,
 707025,
 836461,
 912534,
 993997,
 860997,
 993997,
 877285,
 759000,
 917000,
 936000,
 971000,
 834000,
 1013000,
 986689,
 1069689,
 1120689,
 887689,
 788913,
 1035000,
 925000,
 925000,
 815000,
 916050,
 808050,
 1048050,
 935050,
 995000,
 854328,
 914328,
 976592,
 999614,
 1031943,
 1022930,
 1055259,
 880689,
 992689,
 1043689,
 1143689,
 949999,
 1049999,
 1299999,
 1199999,
 963037,
 1004487,
 1031951,
 1066139,
 1228335,
 989000,
 1029000,
 1149000,
 1309000,
 1409000,
 1034000,
 1154000,
 1254000,
 1354000,
 1534000,
 1634000,
 1379000,
 1529000,
 1629000,
 1629000,
 1414000,
 999900,
 1464900,
 999900,
 1235700,
 1419900,
 1235700,
 1109005,
 1335158,
 1479574,
 1643829,
 1248000,
 1348000,
 1448000,
 1588000,
 1728000,
 ...]

In [4]:
cars = pd.read_csv('e:/cars_cleaned.csv')

In [7]:
cars['Ex-Showroom_Price (in Rs.)'].min()

236447

In [8]:
cars['Ex-Showroom_Price (in Rs.)'].max()

212155397